name: CICD-MongoDB

on:
  push:
    branches: [ "*" ]
    paths-ignore:
      - 'doc/**'
  pull_request:
    branches: [ "*" ]
    paths-ignore:
      - 'doc/**'

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  CICD:

    runs-on: self-hosted
    name: CICD-MongoDB
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: audit

    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
    - name: Enable MongoDB docker
      run: |
        source scripts/start-happypath.sh
        ATD_MEMSZ=8g run_workload -d test -i mongo -j '.writableFS=true | .uids+=[999] | .entrypoint+=["mongod"]'
