name: Debian Builds

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    name: Debian Builds
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: audit

    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
    - name: Debian builds
      shell: docker build --progress=plain -t acond -f {0} .
      run: |
        FROM rust:slim
        RUN apt update -y && \
          apt upgrade -y && \
          apt install -y pkg-config libssl-dev git musl-tools protobuf-compiler libprotobuf-dev
        COPY . ACON
        RUN cd ACON/acond && \
          CARGO_BUILD_RUSTFLAGS=-Ctarget-feature=-crt-static cargo build --release
